<?php

namespace AppBundle\Repository;

/**
 * insecteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class insecteRepository extends \Doctrine\ORM\EntityRepository
{
}
